select  * from tblCompany_Market ORDER BY Company_MarketID DESC
select  * from tblCompanies
select  * from ewhCompanyLog
select  * from tblContacts
select  * from tblCompany_Volume_Status
select  * from tblCompany_TradeShow
select  * from tblCompany_Article
select  * from tblFinancialPerformance
select  * from tblFacilities
select  * from tblMergersAcquisitions
select  * from tblKnownClients
select  * from tblArticle_MergeAcq
select  * from tblKnownClient_Service
select  * from tblKnownClient_Scale
select  * from tblInspections
select  * from tblContractorUpdate_Service
select  * from tblContractorUpdates
select  * from tblFacility_Service
select  * from tblFacility_Service
select  * from tblFacType_Facility
select  * from tblServiceValues
select  * from edtCompany_Market
select  * from edtCompanies
select  * from edtCompany_TradeShow
select  * from edtCompany_Volume_Status
select  * from edtContacts
select  * from edtFinancialPerformance
select  * from edtCompany_Article
select  * from edtFacilities
select  * from edtMergersAcquisitions
select  * from edtKnownClients
select  * from edtKnownClient_Service
select  * from edtArticle_MergeAcq
select  * from edtKnownClient_Scale
select  * from edtInspections
select  * from edtFacType_Facility
select  * from edtFacility_Service
select  * from edtFacility_Service
select  * from edtFacility_Service
select  * from edtContractorUpdates
select  * from edtContractorUpdate_Service
select  * from edtServiceValues
select  * from edtServiceValues
